"""create source items table

Revision ID: 0703f131f6ae
Revises: 559c5ffc3273
Create Date: 2026-06-04 11:19:40.158040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0703f131f6ae'
down_revision = '559c5ffc3273'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=500), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('guid', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('media_thumbnail', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_items_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_source_items_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_guid'), ['guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_normalized_url'), ['normalized_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_items_status'))
        batch_op.drop_index(batch_op.f('ix_source_items_source_type'))
        batch_op.drop_index(batch_op.f('ix_source_items_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_source_items_platform'))
        batch_op.drop_index(batch_op.f('ix_source_items_normalized_url'))
        batch_op.drop_index(batch_op.f('ix_source_items_id'))
        batch_op.drop_index(batch_op.f('ix_source_items_guid'))
        batch_op.drop_index(batch_op.f('ix_source_items_domain'))
        batch_op.drop_index(batch_op.f('ix_source_items_content_hash'))
        batch_op.drop_index(batch_op.f('ix_source_items_collected_at'))

    op.drop_table('source_items')
    # ### end Alembic commands ###
