"""Add GLOBAL_SEARCH to SourceType

Revision ID: 1a696bbad03b
Revises: 93a03c74c024
Create Date: 2026-05-31 16:34:11.543342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a696bbad03b'
down_revision = '93a03c74c024'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.alter_column('keyword_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('general', 'brand', 'competitor', 'person', 'service', 'location', 'hashtag', 'negative_phrase', 'positive_phrase', name='keywordtype'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.alter_column('keyword_type',
               existing_type=sa.Enum('general', 'brand', 'competitor', 'person', 'service', 'location', 'hashtag', 'negative_phrase', 'positive_phrase', name='keywordtype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
