"""create_source_items_table

Revision ID: 1d09402c6678
Revises: 308ae8695f74
Create Date: 2026-06-04 14:31:17.794567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d09402c6678'
down_revision = '308ae8695f74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.drop_index('idx_analysis_analyzed_at')

    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.drop_index('idx_mention_project_collected')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.create_index('idx_mention_project_collected', ['project_id', 'collected_at'], unique=False)

    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.create_index('idx_analysis_analyzed_at', ['analyzed_at'], unique=False)

    # ### end Alembic commands ###
