"""Add scan_schedule_id and scan_logs

Revision ID: 46a47d2d65f8
Revises: 7cb17a41ced9
Create Date: 2026-06-23 09:22:51.467555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '46a47d2d65f8'
down_revision = '7cb17a41ced9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(bind)
    if 'scan_logs' not in inspector.get_table_names():
        op.create_table('scan_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('scan_schedule_id', sa.Integer(), nullable=True),
        sa.Column('job_id', sa.Integer(), nullable=True),
        sa.Column('level', sa.String(length=20), nullable=True),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('meta_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('scan_logs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_scan_logs_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_scan_logs_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_scan_logs_job_id'), ['job_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_scan_logs_scan_schedule_id'), ['scan_schedule_id'], unique=False)

    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_schedule_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_crawl_jobs_scan_schedule_id'), ['scan_schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_jobs_scan_schedule_id'))
        batch_op.drop_column('scan_schedule_id')

    with op.batch_alter_table('scan_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_logs_scan_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_scan_logs_job_id'))
        batch_op.drop_index(batch_op.f('ix_scan_logs_id'))
        batch_op.drop_index(batch_op.f('ix_scan_logs_created_at'))

    op.drop_table('scan_logs')
    # ### end Alembic commands ###
