"""Add next_retry_at and payload to NotificationDeliveryLog

Revision ID: 5bd0ccefc51f
Revises: 46a47d2d65f8
Create Date: 2026-06-23 09:45:48.622770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
"""Add next_retry_at and payload to NotificationDeliveryLog

Revision ID: 5bd0ccefc51f
Revises: 46a47d2d65f8
Create Date: 2026-06-23 09:45:48.622770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5bd0ccefc51f'
down_revision = '46a47d2d65f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_delivery_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_notification_delivery_logs_next_retry_at'), ['next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_delivery_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_delivery_logs_next_retry_at'))
        batch_op.drop_column('next_retry_at')
        batch_op.drop_column('payload')
    # ### end Alembic commands ###
