"""add_verification_fields

Revision ID: 5fe3f0fbfb82
Revises: fab61847c68d
Create Date: 2026-06-11 21:54:38.278808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5fe3f0fbfb82'
down_revision = 'fab61847c68d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('verification_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('original_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('canonical_url', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mentions_verification_status'), ['verification_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentions_verification_status'))
        batch_op.drop_column('canonical_url')
        batch_op.drop_column('original_url')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_error')
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###
