"""add_notification_delivery_logs

Revision ID: 7cb17a41ced9
Revises: a34bcad08e54
Create Date: 2026-06-22 09:56:18.268201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7cb17a41ced9'
down_revision = 'a34bcad08e54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('mention_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('destination', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_delivery_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_delivery_logs_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_delivery_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_delivery_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_delivery_logs_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_delivery_logs_mention_id'), ['mention_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_delivery_logs_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_delivery_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_delivery_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_notification_delivery_logs_mention_id'))
        batch_op.drop_index(batch_op.f('ix_notification_delivery_logs_incident_id'))
        batch_op.drop_index(batch_op.f('ix_notification_delivery_logs_id'))
        batch_op.drop_index(batch_op.f('ix_notification_delivery_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_notification_delivery_logs_alert_id'))

    op.drop_table('notification_delivery_logs')
    # ### end Alembic commands ###
