"""add_report_exports_table

Revision ID: 8842624c78e7
Revises: 5bd0ccefc51f
Create Date: 2026-06-23 14:24:37.794763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8842624c78e7'
down_revision = '5bd0ccefc51f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute('''
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'exportstatus') THEN
                CREATE TYPE exportstatus AS ENUM ('pending', 'running', 'success', 'failed');
            END IF;
        END$$;
        ''')
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(bind)
    if 'report_exports' not in inspector.get_table_names():
        # Ensure enum is not recreated
        op.create_table('report_exports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('report_type', sa.String(length=50), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.Column('requested_by', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='exportstatus', create_type=False), nullable=True),
        sa.Column('file_path', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('report_exports', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_report_exports_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_report_exports_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_report_exports_project_id'), ['project_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_report_exports_requested_by'), ['requested_by'], unique=False)
            batch_op.create_index(batch_op.f('ix_report_exports_status'), ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_exports_status'))
        batch_op.drop_index(batch_op.f('ix_report_exports_requested_by'))
        batch_op.drop_index(batch_op.f('ix_report_exports_project_id'))
        batch_op.drop_index(batch_op.f('ix_report_exports_id'))
        batch_op.drop_index(batch_op.f('ix_report_exports_created_at'))

    op.drop_table('report_exports')
    # ### end Alembic commands ###
