"""Add Vietnamese Context fields to AIAnalysis

Revision ID: 93a03c74c024
Revises: 022
Create Date: 2026-05-31 16:06:25.117226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a03c74c024'
down_revision = '022'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis', sa.Column('vietnamese_context_label', sa.String(length=100), nullable=True))
    op.add_column('ai_analysis', sa.Column('tone', sa.String(length=50), nullable=True))
    op.add_column('ai_analysis', sa.Column('sarcasm_possible', sa.Boolean(), nullable=True))
    op.add_column('ai_analysis', sa.Column('complaint_type', sa.String(length=100), nullable=True))
    op.add_column('ai_analysis', sa.Column('sensitive_signal', sa.Boolean(), nullable=True))
    op.add_column('ai_analysis', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_analysis', 'explanation')
    op.drop_column('ai_analysis', 'sensitive_signal')
    op.drop_column('ai_analysis', 'complaint_type')
    op.drop_column('ai_analysis', 'sarcasm_possible')
    op.drop_column('ai_analysis', 'tone')
    op.drop_column('ai_analysis', 'vietnamese_context_label')
    # ### end Alembic commands ###
