"""Add Meta integrations

Revision ID: 9ce21a601064
Revises: 5fe3f0fbfb82
Create Date: 2026-06-20 13:46:52.460370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9ce21a601064'
down_revision = '5fe3f0fbfb82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_states_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_states_state_token'), ['state_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth_states_user_id'), ['user_id'], unique=False)

    op.create_table('social_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('granted_scopes_json', sa.JSON(), nullable=True),
    sa.Column('missing_scopes_json', sa.JSON(), nullable=True),
    sa.Column('token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_integrations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_integrations_user_id'), ['user_id'], unique=False)

    op.create_table('social_integration_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['social_integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_integration_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_integration_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_integration_accounts_integration_id'), ['integration_id'], unique=False)

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_integration_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_integration_accounts_integration_id'))
        batch_op.drop_index(batch_op.f('ix_social_integration_accounts_id'))

    op.drop_table('social_integration_accounts')
    with op.batch_alter_table('social_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_integrations_user_id'))
        batch_op.drop_index(batch_op.f('ix_social_integrations_id'))

    op.drop_table('social_integrations')
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_states_state_token'))
        batch_op.drop_index(batch_op.f('ix_oauth_states_id'))

    op.drop_table('oauth_states')
    # ### end Alembic commands ###
