"""enhance_worker_status

Revision ID: a34bcad08e54
Revises: 5fe3f0fbfb82
Create Date: 2026-06-21 10:42:24.262328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a34bcad08e54'
down_revision = '5fe3f0fbfb82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('scan_interval_minutes', sa.Integer(), nullable=False, server_default=sa.text('15')))
        batch_op.add_column(sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_finished_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_scan_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('skipped_due_to_lock_count', sa.Integer(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_status', schema=None) as batch_op:
        batch_op.drop_column('skipped_due_to_lock_count')
        batch_op.drop_column('next_run_at')
        batch_op.drop_column('last_scan_count')
        batch_op.drop_column('last_error_at')
        batch_op.drop_column('last_success_at')
        batch_op.drop_column('last_finished_at')
        batch_op.drop_column('last_started_at')
        batch_op.drop_column('scan_interval_minutes')
        batch_op.drop_column('locked_at')
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###
