"""Add mention visits

Revision ID: fab61847c68d
Revises: 39818fa14818
Create Date: 2026-06-10 21:50:13.634925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fab61847c68d'
down_revision = '39818fa14818'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mention_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mention_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('visited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mention_visits', schema=None) as batch_op:
        batch_op.create_index('idx_mention_visits_project_time', ['project_id', 'visited_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mention_visits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mention_visits_mention_id'), ['mention_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mention_visits_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mention_visits_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mention_visits_visited_at'), ['visited_at'], unique=False)

    pass
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.alter_column('sentiment',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('positive', 'neutral', 'negative', name='sentimentscore'),
               existing_nullable=False)

    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_visited_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.drop_column('last_visited_at')
        batch_op.drop_column('visit_count')

    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.alter_column('sentiment',
               existing_type=sa.Enum('positive', 'neutral', 'negative', name='sentimentscore'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    pass

    with op.batch_alter_table('mention_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mention_visits_visited_at'))
        batch_op.drop_index(batch_op.f('ix_mention_visits_user_id'))
        batch_op.drop_index(batch_op.f('ix_mention_visits_project_id'))
        batch_op.drop_index(batch_op.f('ix_mention_visits_mention_id'))
        batch_op.drop_index(batch_op.f('ix_mention_visits_id'))
        batch_op.drop_index('idx_mention_visits_project_time')

    op.drop_table('mention_visits')
    # ### end Alembic commands ###
